import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import {
  chmodSync,
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import test from 'node:test';
import {
  normalizeCSharpSpec,
  syncGeneratedSource,
} from './generate-csharp.mjs';

const oldRef = '#/components/schemas/PlayoffCompetition.Cfp';
const newRef = '#/components/schemas/Cfp';
function fixture() {
  return {
    components: {
      schemas: {
        'PlayoffCompetition.Cfp': { type: 'string', enum: ['cfp'] },
        PlayoffCompetition: { type: 'string', enum: ['cfp'] },
        CfpPlayoff: { properties: { competition: { $ref: oldRef } } },
        'Preview.Other': { type: 'object' },
      },
    },
    paths: {
      '/test': { allOf: [{ $ref: oldRef }], items: { $ref: oldRef } },
    },
    discriminator: {
      mapping: { cfp: oldRef, short: 'PlayoffCompetition.Cfp' },
    },
    description: oldRef,
  };
}

test('C# alias rewrites references without mutating shared schemas or wire values', () => {
  const input = fixture();
  const original = structuredClone(input);
  const result = normalizeCSharpSpec(input);
  assert.deepEqual(input, original);
  assert.deepEqual(result.components.schemas.Cfp, {
    type: 'string',
    enum: ['cfp'],
  });
  assert(!('PlayoffCompetition.Cfp' in result.components.schemas));
  assert.equal(
    result.components.schemas.CfpPlayoff.properties.competition.$ref,
    newRef,
  );
  assert.equal(result.paths['/test'].allOf[0].$ref, newRef);
  assert.equal(result.paths['/test'].items.$ref, newRef);
  assert.deepEqual(result.discriminator.mapping, {
    cfp: newRef,
    short: newRef,
  });
  assert.equal(result.description, oldRef);
  assert.deepEqual(
    result.components.schemas.PlayoffCompetition,
    input.components.schemas.PlayoffCompetition,
  );
  assert.deepEqual(
    result.components.schemas['Preview.Other'],
    input.components.schemas['Preview.Other'],
  );
});

test('existing target names fail closed, including differently cased names', () => {
  for (const name of ['Cfp', 'cfp', 'CFP', 'Cfp.Other']) {
    const spec = fixture();
    spec.components.schemas[name] = { type: 'string', enum: ['cfp'] };
    assert.throws(() => normalizeCSharpSpec(spec), /collision/);
  }
});

test('missing or changed member enum requires explicit compatibility review', () => {
  const missing = fixture();
  delete missing.components.schemas['PlayoffCompetition.Cfp'];
  assert.throws(() => normalizeCSharpSpec(missing), /Missing schema/);
  for (const schema of [
    { type: 'string', enum: ['other'] },
    { type: 'string', enum: ['cfp', 'other'] },
  ]) {
    const spec = fixture();
    spec.components.schemas['PlayoffCompetition.Cfp'] = schema;
    assert.throws(() => normalizeCSharpSpec(spec), /cfp-only/);
  }
});

const generated =
  '// <auto-generated/>\n[global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]\n';
function temporary(t) {
  const root = mkdtempSync(join(tmpdir(), 'cfbd-csharp-test-'));
  t.after(() => rmSync(root, { recursive: true, force: true }));
  return root;
}
function write(root, path, content) {
  const target = join(root, path);
  mkdirSync(resolve(target, '..'), { recursive: true });
  writeFileSync(target, content);
}

test('sync removes obsolete nested enum and preserves project and handwritten files', (t) => {
  const root = temporary(t);
  const stage = join(root, 'stage');
  const target = join(root, 'sdk');
  write(stage, 'ApiClient.cs', generated);
  write(stage, 'Models/Cfp.cs', generated + 'new flat enum');
  write(stage, 'Models/PlayoffCompetition.cs', generated);
  write(stage, 'kiota-lock.json', '{}');
  write(
    target,
    'Models/PlayoffCompetition/Cfp.cs',
    generated + 'stale nested enum',
  );
  write(target, 'Models/Cfp.cs', generated + 'old flat enum');
  write(target, 'CollegeFootballData.csproj', 'project');
  write(target, 'Custom.cs', 'handwritten');
  write(
    target,
    'Models/LiveGamePlay_rushPash.cs',
    generated + 'published legacy enum',
  );
  write(target, 'obj/Build.cs', generated);
  for (let attempt = 0; attempt < 2; attempt++) {
    syncGeneratedSource(stage, target);
    assert(!existsSync(join(target, 'Models/PlayoffCompetition/Cfp.cs')));
    assert.equal(
      readFileSync(join(target, 'Models/Cfp.cs'), 'utf8'),
      generated + 'new flat enum',
    );
    assert.equal(
      readFileSync(join(target, 'CollegeFootballData.csproj'), 'utf8'),
      'project',
    );
    assert.equal(
      readFileSync(join(target, 'Custom.cs'), 'utf8'),
      'handwritten',
    );
    assert(existsSync(join(target, 'obj/Build.cs')));
    assert(existsSync(join(target, 'Models/LiveGamePlay_rushPash.cs')));
  }
});

test('sync fails before cleanup when generated files would overwrite handwritten code', (t) => {
  const root = temporary(t);
  const stage = join(root, 'stage');
  const target = join(root, 'sdk');
  write(stage, 'ApiClient.cs', generated);
  write(target, 'ApiClient.cs', 'handwritten');
  write(target, 'Stale.cs', generated);
  assert.throws(() => syncGeneratedSource(stage, target), /non-Kiota/);
  assert(existsSync(join(target, 'Stale.cs')));
});

test('generation failure exits nonzero and leaves SDK untouched', (t) => {
  const root = temporary(t);
  const spec = join(root, 'spec.json');
  writeFileSync(spec, JSON.stringify(fixture()));
  write(root, 'sdk/src/CollegeFootballData.csproj', 'project');
  write(root, 'sdk/src/Models/PlayoffCompetition/Cfp.cs', generated);
  write(root, 'bin/kiota', '#!/bin/sh\nexit 1\n');
  // Use a private executable to test failure without invoking the real generator.
  chmodSync(join(root, 'bin/kiota'), 0o755);
  const result = spawnSync(
    process.execPath,
    ['scripts/generate-csharp.mjs', spec, join(root, 'sdk')],
    {
      env: { ...process.env, PATH: `${join(root, 'bin')}:${process.env.PATH}` },
    },
  );
  assert.notEqual(result.status, 0);
  assert.match(result.stderr.toString(), /Kiota generation failed/);
  assert(existsSync(join(root, 'sdk/src/Models/PlayoffCompetition/Cfp.cs')));
});

test('real TSOA schema retains full enum and cfp-only member contract', () => {
  const input = JSON.parse(readFileSync('build/swagger.json', 'utf8'));
  const output = normalizeCSharpSpec(input);
  assert.equal(
    output.components.schemas.CfpPlayoff.properties.competition.$ref,
    newRef,
  );
  assert.deepEqual(
    output.components.schemas.PlayoffCompetition,
    input.components.schemas.PlayoffCompetition,
  );
  assert.deepEqual(output.components.schemas.Cfp.enum, ['cfp']);
  assert(!JSON.stringify(output).includes(`"$ref":"${oldRef}"`));
});

test('validation exits nonzero on build or pack failure', (t) => {
  for (const failedCommand of ['build', 'pack']) {
    const root = temporary(t);
    write(root, 'spec.json', JSON.stringify(fixture()));
    write(root, 'sdk/src/CollegeFootballData.csproj', 'project');
    write(root, 'sdk/src/ApiClient.cs', generated);
    write(
      root,
      'bin/kiota',
      `#!/bin/sh
while [ "$1" != "--output" ]; do shift; done
mkdir -p "$2"
cp '${root}/sdk/src/ApiClient.cs' "$2/ApiClient.cs"
`,
    );
    write(
      root,
      'bin/dotnet',
      `#!/bin/sh
echo "$1" >> '${root}/commands'
if [ "$1" = '${failedCommand}' ]; then exit 1; fi
`,
    );
    chmodSync(join(root, 'bin/kiota'), 0o755);
    chmodSync(join(root, 'bin/dotnet'), 0o755);
    const result = spawnSync(
      process.execPath,
      ['scripts/verify-csharp.mjs', join(root, 'spec.json'), join(root, 'sdk')],
      {
        env: {
          ...process.env,
          PATH: `${join(root, 'bin')}:${process.env.PATH}`,
        },
      },
    );
    assert.notEqual(result.status, 0);
    assert.match(
      result.stderr.toString(),
      new RegExp(`dotnet ${failedCommand} failed`),
    );
    assert.equal(
      readFileSync(join(root, 'commands'), 'utf8'),
      failedCommand === 'build' ? 'build\n' : 'build\npack\n',
    );
  }
});

test('release pushes only after successful generation and validation', () => {
  const workflow = readFileSync('.github/workflows/release.yml', 'utf8');
  const job = workflow.slice(workflow.indexOf('  buildCSharp:'));
  assert(!job.includes('continue-on-error: true'));
  assert(!job.includes('always()'));
  assert(job.indexOf('generate-csharp.mjs') < job.indexOf('verify-csharp.mjs'));
  assert(job.indexOf('verify-csharp.mjs') < job.indexOf('git push'));
  assert(job.includes("version: 'v1.35.0'"));
});
