import { spawnSync } from 'node:child_process';
import {
  copyFileSync,
  existsSync,
  mkdirSync,
  mkdtempSync,
  readdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

// This compatibility alias belongs only to the C# input, not the public spec.
export function normalizeCSharpSpec(input) {
  const spec = structuredClone(input);
  const schemas = spec.components?.schemas;
  const source = 'PlayoffCompetition.Cfp';
  const target = 'Cfp';
  if (!schemas?.[source]) throw new Error(`Missing schema: ${source}`);
  if (
    Object.keys(schemas).some(
      (name) =>
        name.toLowerCase() === target.toLowerCase() ||
        name.toLowerCase().startsWith(`${target.toLowerCase()}.`),
    )
  ) {
    throw new Error(`C# schema name collision: ${target}`);
  }
  const schema = schemas[source];
  if (
    schema.type !== 'string' ||
    schema.enum?.length !== 1 ||
    schema.enum[0] !== 'cfp'
  ) {
    throw new Error('PlayoffCompetition.Cfp is no longer the cfp-only enum');
  }
  schemas[target] = schema;
  delete schemas[source];
  const oldRef = `#/components/schemas/${source}`;
  const newRef = `#/components/schemas/${target}`;
  function visit(value) {
    if (!value || typeof value !== 'object') return;
    for (const [key, child] of Object.entries(value)) {
      if (key === '$ref' && child === oldRef) value[key] = newRef;
      else if (key === 'discriminator' && child?.mapping) {
        for (const [tag, ref] of Object.entries(child.mapping)) {
          if (ref === oldRef || ref === source) child.mapping[tag] = newRef;
        }
        visit(child);
      } else visit(child);
    }
  }
  visit(spec);
  return spec;
}

function files(root, prefix = '') {
  return readdirSync(join(root, prefix), { withFileTypes: true }).flatMap(
    (entry) => {
      const path = join(prefix, entry.name);
      // Build artifacts are not generated SDK source.
      if (entry.isDirectory()) {
        return ['bin', 'obj'].includes(entry.name) ? [] : files(root, path);
      }
      return entry.isFile() ? [path] : [];
    },
  );
}

function isGenerated(path) {
  return (
    path.endsWith('.cs') &&
    readFileSync(path, 'utf8').startsWith('// <auto-generated/>') &&
    readFileSync(path, 'utf8').includes('GeneratedCode("Kiota",')
  );
}

export function syncGeneratedSource(generated, destination) {
  const incoming = files(generated);
  if (!incoming.includes('ApiClient.cs')) {
    throw new Error('Kiota did not generate ApiClient.cs');
  }
  // Check before changing anything; preserve project files and handwritten code.
  for (const file of incoming) {
    const target = join(destination, file);
    if (
      existsSync(target) &&
      file !== 'kiota-lock.json' &&
      !isGenerated(target)
    ) {
      throw new Error(`Refusing to overwrite non-Kiota file: ${target}`);
    }
  }
  for (const file of files(destination)) {
    // This unused enum shipped in 5.30.1 (including its historical typo).
    // Retain that public type; it is unrelated to the unpublished nested Cfp.
    const legacyPublicType =
      file === join('Models', 'LiveGamePlay_rushPash.cs');
    if (
      !incoming.includes(file) &&
      !legacyPublicType &&
      isGenerated(join(destination, file))
    ) {
      rmSync(join(destination, file));
    }
  }
  for (const file of incoming) {
    const target = join(destination, file);
    mkdirSync(dirname(target), { recursive: true });
    copyFileSync(join(generated, file), target);
  }
}

export function generateCSharp(specPath, sdkPath) {
  const spec = normalizeCSharpSpec(JSON.parse(readFileSync(specPath, 'utf8')));
  const destination = join(resolve(sdkPath), 'src');
  const project = join(destination, 'CollegeFootballData.csproj');
  if (!existsSync(project)) throw new Error(`Missing SDK project: ${project}`);
  const stage = mkdtempSync(join(tmpdir(), 'cfbd-csharp-'));
  try {
    const input = join(stage, 'api-docs.json');
    const output = join(stage, 'src');
    writeFileSync(input, JSON.stringify(spec, null, 2) + '\n');
    const result = spawnSync(
      'kiota',
      [
        'generate',
        '--language',
        'csharp',
        '--openapi',
        input,
        '--output',
        output,
        '--namespace-name',
        'CollegeFootballData',
      ],
      { stdio: 'inherit' },
    );
    if (result.error) throw result.error;
    if (result.status !== 0) throw new Error('Kiota generation failed');
    syncGeneratedSource(output, destination);
  } finally {
    rmSync(stage, { recursive: true, force: true });
  }
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const [, , spec, sdk] = process.argv;
  if (!spec || !sdk) {
    throw new Error(
      'Usage: node scripts/generate-csharp.mjs <spec.json> <sdk>',
    );
  }
  generateCSharp(spec, sdk);
}
